export { default as imgCard1 } from 'src/assets/img/abstract.jpg'
export { default as imgCard2 } from 'src/assets/img/abstract3.jpg'
export { default as imgcard3 } from 'src/assets/img/abstract4.jpg'
export { default as imgHome } from 'src/assets/img/abstract2.jpg'
export { default as imgHome2 } from 'src/assets/img/abstract22.jpg'
export { default as imgCat } from 'src/assets/img/cat.gif'